# f() -> error

def f():
    print('f called')

f()

g = f
g()
